import {
  LuChartPie,
  LuGalleryVerticalEnd,
  LuHistory,
  LuKey,
  LuLayoutGrid,
  LuShieldCheck,
  LuShieldAlert,
  LuUsers,
} from 'react-icons/lu';
import {
  LuGraduationCap,
  LuBookOpen,
  LuBookText,
  LuCircleHelp,
  LuBrain,
  LuClipboardList,
  LuFileCheck,
  LuTarget,
  LuNotebookPen,
  LuFileText,
  LuBookOpenCheck,
  LuBadgeCheck,
  LuSparkles,
} from 'react-icons/lu';

export const featureIcons = {
  dashboard: LuChartPie,
  auditLog: LuHistory,
  apiKey: LuKey,
  member: LuUsers,
  organization: LuGalleryVerticalEnd,
  exam: LuGraduationCap,
  chapter: LuBookOpen,
  lesson: LuBookText,
  practiceQuestion: LuCircleHelp,
  concept: LuBrain,
  examType: LuClipboardList,
  examInstance: LuFileCheck,
  dailyGoal: LuTarget,
  studyNote: LuNotebookPen,
  documentUpload: LuFileText,
  course: LuBookOpenCheck,
  creatorApplication: LuBadgeCheck,
  platformAdmin: LuShieldCheck,
  trustSafety: LuShieldAlert,
  aiTutor: LuSparkles,
} as const;
